POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "user13",
    "email": "user13@gmail.com",
    "referrer": "23fe28f6-1e8e-439e-bb05-ebad204e59ab"
}

###

GET http://localhost:3333/invites/e799318b-da8c-4a57-b05f-5f8586708c5f

###

GET http://localhost:3333/subscribers/e799318b-da8c-4a57-b05f-5f8586708c5f/ranking/clicks

###

GET http://localhost:3333/subscribers/e799318b-da8c-4a57-b05f-5f8586708c5f/ranking/count

###

GET http://localhost:3333/subscribers/e799318b-da8c-4a57-b05f-5f8586708c5f/ranking/position

###

GET http://localhost:3333/ranking