POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "karla1",
    "email": "karla1@gmail.com",
    "referrer": "fc02c34e-b0db-4879-a1a6-4af9326f8f99"
}

###

GET http://localhost:3333/invites/fc02c34e-b0db-4879-a1a6-4af9326f8f99

###

GET http://localhost:3333/subscribers/fc02c34e-b0db-4879-a1a6-4af9326f8f99/ranking/clicks

###

GET http://localhost:3333/subscribers/fc9a165c-bec0-404b-b854-84987e9dbd90/ranking/count

###

GET http://localhost:3333/subscribers/fc02c34e-b0db-4879-a1a6-4af9326f8f99/ranking/position

###

GET http://localhost:3333/ranking